config/routes.rb
Rails.application.routes.draw do
  resources :lobbies

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'welcome#index'
  get 'welcome/index'

  resources :rooms do
    collection do
      get 'prepare'
      post 'prepare'

      get 'battle'
      post 'battle'
    end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lobby.rb
class Lobby < ApplicationRecord
  validates :loginname, presence: true
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  before_action :set_lobby, only: [ :show, :edit, :update, :destroy]
  before_action :require_user
  skip_before_action :require_login, only: [:index, :show]

  # GET /lobbies
  # GET /lobbies.json
  def index
    @lobbies = Lobby.all.order(:applytime)
    respond_to do |format|
      format.html
      format.json {
        @lobbies = Lobby.where.not(applytime: nil) #= Lobby.where( 'applytime > ?', params[:my_applytime])
      }
    end
  end

  # GET /lobbies/1
  # GET /lobbies/1.json
  def show
    respond_to do |format|
      format.html
      format.json { @lobby }
    end
  end

  # GET /lobbies/new
  def new
    @lobby = Lobby.new
  end

  # GET /lobbies/1/edit
  def edit
  end

  # POST /lobbies
  # POST /lobbies.json
  def create
    @lobby = Lobby.new(lobby_params)

    respond_to do |format|
      if @lobby.save
        format.html
        format.json { render :show, status: :created, location: @lobby }
      else
        format.html { render :new }
        format.json { render json: @lobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lobbies/1
  # PATCH/PUT /lobbies/1.json
  def update
    respond_to do |format|
      if @lobby.update(lobby_params)
        format.html
        format.json { render :show, status: :ok, location: @lobby }
      else
        format.html { render :edit }
        format.json { render json: @lobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lobbies/1
  # DELETE /lobbies/1.json
  def destroy
    @lobby.destroy
    respond_to do |format|
      format.html { redirect_to lobbies_url, notice: 'Lobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lobby
      @lobby = Lobby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lobby_params
      params.permit(:loginname, :applytime)
    end
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
end

app/views/lobbies/_form.html.erb
<%= form_with(model: lobby, class: 'lobbyform'+classnum) do |form| %>
  <% if lobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lobby.errors.count, "error") %> prohibited this lobby from being saved:</h2>

      <ul>
      <% lobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :loginname %>
    <%= form.text_field :loginname, id: :lobby_loginname, class: 'myloginname'+classnum %>
  </div>

  <div class="field">
    <%= form.label :applytime %>
    <%= form.hidden_field :applytime, :value => '' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lobbies/edit.html.erb
<h1>Editing Lobby</h1>

<%= render 'form', lobby: @lobby, classnum: '1'%>

<%= link_to 'Show', @lobby %> |
<%= link_to 'Back', lobbies_path %>

app/views/lobbies/edit.js.erb
$('#lobby-form').html("<%= j (render 'form') %>");

app/views/lobbies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lobbies</h1>

<table>
  <thead>
    <tr>
      <th>Loginname</th>
      <th>Applytime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lobbies.each do |lobby| %>
      <tr>
        <td><%= lobby.loginname %></td>
        <td><%= lobby.applytime %></td>
        <td><%= link_to 'Show', lobby %></td>
        <td><%= link_to 'Edit', edit_lobby_path(lobby) %></td>
        <td><%= link_to 'Destroy', lobby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lobby', new_lobby_path %>

app/views/lobbies/new.html.erb
<h1>New Lobby</h1>

<%= render 'form', lobby: @lobby %>

<%= link_to 'Back', lobbies_path %>

app/views/lobbies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loginname:</strong>
  <%= @lobby.loginname %>
</p>

<p>
  <strong>Applytime:</strong>
  <%= @lobby.applytime %>
</p>

<%# link_to 'Edit', edit_lobby_path(@lobby) %> 
<%# link_to 'Back', lobbies_path %>