config/routes.rb
Rails.application.routes.draw do
  resources :lobbies

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'welcome#index'
  get 'welcome/index'

  resources :rooms do
    collection do
      get 'prepare'
      post 'prepare'

      get 'battle'
      post 'battle'
    end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :loginname, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @lobby = Lobby.new
    @room = Room.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:loginname, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: 'userform'+classnum) do |form|%>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"+classnum>
    <%= form.label :loginname %>
    <%= form.text_field :loginname, id: :user_loginname,:value => '', class: 'myloginname'+classnum%>
  </div>

  <div class="field"+classnum>
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'mypassword'+classnum %>
  </div>

  <div class="field"+classnum>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions"+classnum>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Loginname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.loginname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user, classnum: '1'%>
<%= render '/lobbies/form', lobby: @lobby, classnum: '2'%>
<%# render '/rooms/form', lobby: @room, classnum: '3'%>
<%= form_with(model: @room, class: 'roomform3') do |form| %>
  <div class="field">
    <%= form.label :loginname %>
    <%= form.text_field :loginname, id: :room_loginname, :value => '', class: 'myloginname3' %>
  </div>
  <div class="actions" style='visibility:hidden'>
    <%= form.submit() %>
  </div>
<% end %>
<button class='submitbutton' style='visibility:hidden'>
Create Account
</button>
<%= link_to 'Back', login_url %>
<script>

$('.lobbyform2').hide();
$('.roomform3').hide();/*
$('.submitbutton').on('click', function(){
  var myname = $('.myloginname1').val();
  $('.myloginname2').val(myname);
  $('.myloginname3').val(myname);
  if(myname.length>0){
    $('.userform1').submit();
    //submitforms();
  }
  window.location.href = '/login/';
});
function submitforms(){
  $('.userform1').submit();
  setTimeout(() => {
    $('.lobbyform2').submit();
    setTimeout(() => {
      $('.roomform3').submit();
    }, 500);
  }, 500);
}*/
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loginname:</strong>
  <%= @user.loginname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', login_url %>